version: "3.8"

services:

  simplydash:
    container_name: simplydash
    hostname: simplydash
    image: simplydash:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /tmp/simplydash/config:/app/config
      - /tmp/simplydash/icons:/app/icons
