apps:
    - name: google
      link: https://google.com
      group: apps
      healthcheck:
          disable: true
    - name: Adguard  Home
      link: https://adguard.yavin.xyz
      group: apps

docker:
    local:
        host: "unix:///var/run/docker.sock"
    prod:
        host: "https://docker.prod.yavin.xyz:2375"

web:
    name: hello
    theme: dark
    background: "#0a0a0a"
    background_image: ""
